# Generated by Django 3.0.2 on 2020-03-11 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='descrip',
            field=models.TextField(default=datetime.date(2020, 3, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='hum',
            field=models.TextField(default=datetime.date(2020, 3, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.URLField(default=datetime.date(2020, 3, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='pressure',
            field=models.TextField(default=datetime.date(2020, 3, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='temp',
            field=models.TextField(default=datetime.date(2020, 3, 11)),
            preserve_default=False,
        ),
    ]
