# Generated by Django 3.0.2 on 2020-03-23 09:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_remove_city_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 9, 7, 28, 922962, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
